Repository DefCon-Apps/DefCon-FE, pull requests merged in 2023-08, with the labels that each got.

#132 [FIX] Project List 항목 누락 이슈 해결
  pages/Projects/Projects.tsx
Labels: bug

#135 [FIX] ProjectList 간격 조정
  pages/Projects/ProjectSection.tsx
  pages/Projects/Projects.tsx
Labels: fix

#136 [FIX] 경로명 소문자 변경 & 타이틀 메타 데이터 전역 적용
  pages/Designs/index.tsx
  pages/Main/Index.tsx
  pages/Members/index.tsx
  pages/Privacy/index.tsx
  pages/Projects/index.tsx
  pages/_app.tsx
  pages/designs/CrabIntro.tsx
  pages/designs/Designs.tsx
  pages/designs/LogoIntro.tsx
  pages/designs/index.tsx
  pages/index.tsx
  pages/main/Index.tsx
  pages/main/Main.tsx
  pages/main/MainAwards.tsx
  pages/main/MainHistory.tsx
  pages/main/MainTitle.tsx
  pages/main/MainWorks.tsx
  pages/main/index.tsx
  pages/members/Members.tsx
  pages/members/MembersDetail.tsx
  pages/members/MembersList.tsx
  pages/members/MembersListItem.tsx
  pages/members/MembersRectangle.tsx
  pages/members/MembersTitle.tsx
  pages/members/index.tsx
  pages/privacy/Privacy.tsx
  pages/privacy/PrivacyContents.tsx
  pages/privacy/index.tsx
  pages/projects/ProjectList.tsx
  pages/projects/ProjectListItem.tsx
  pages/projects/ProjectSection.tsx
  pages/projects/Projects.tsx
  pages/projects/[ProjectDetail].tsx
  pages/projects/index.tsx
  src/Common/Footer.tsx
  src/Common/Header.tsx
Labels: dev, fix

#138 [FIX] Build Error 해결
  pages/designs/index.tsx
  pages/index.tsx
  pages/main/index.tsx
  pages/members/index.tsx
  pages/privacy/index.tsx
  pages/projects/index.tsx
Labels: bug

#139 [FIX] Build Error 해결
  pages/main/Index.tsx
Labels: bug

#141 [DEV] 프로젝트 상세 페이지 이미지 슬라이더 개선
  pages/projects/[ProjectDetail].tsx
Labels: dev

#143 [FIX] Project List 페이지 개선사항 반영
  pages/projects/ProjectListItem.tsx
  pages/projects/Projects.tsx
Labels: fix

#144 [FIX] ProjectList Reverse
  pages/projects/Projects.tsx
Labels: fix

#148 [FIX] Members 페이지 너비 수정
  pages/members/Members.tsx
Labels: fix

#150 [FIX] 프로젝트 페이지 로딩 표시 구현
  pages/projects/Projects.tsx
  pages/projects/[ProjectDetail].tsx
  src/Common/Loader.tsx
Labels: fix

#154 [FIX] 모바일 페이지 너비 개선
  pages/members/Members.tsx
  pages/privacy/PrivacyContents.tsx
  pages/projects/ProjectSection.tsx
  pages/projects/[ProjectDetail].tsx
Labels: bug

#152 [FIX] Main 페이지 개선
  pages/main/MainAwards.tsx
  pages/main/MainHistory.tsx
  pages/main/MainTitle.tsx
  pages/main/MainWorks.tsx
Labels: bug

#156 [FIX] 모바일 반응형 페이지 개선
  pages/designs/CrabIntro.tsx
  pages/designs/LogoIntro.tsx
  pages/main/MainTitle.tsx
  pages/members/Members.tsx
  pages/projects/ProjectSection.tsx
Labels: bug
