Repository DefCon-Apps/DefCon-FE, pull requests merged in 2023-03, with the labels that each got.

#93 [FIX] Main 페이지 디테일 개선 1
  pages/Main/MainAwards.tsx
  pages/Main/MainHistory.tsx
Labels: enhancement

#94 [FIX] Main 페이지 디테일 개선 2
  pages/Main/MainTitle.tsx
  pages/Main/MainWorks.tsx
Labels: enhancement

#97 [FIX] Crab 컴포넌트 내 img 태그 제거
  pages/Designs/CrabIntro.tsx
  pages/Main/MainTitle.tsx
  pages/Projects/ProjectListItem.tsx
  src/Common/Crab.tsx
Labels: enhancement

#98 [FIX] Main 페이지 디테일 개선작업 - 1
  pages/Main/MainAwards.tsx
  pages/Main/MainHistory.tsx
Labels: enhancement

#103 [FIX] Main 페이지 API 호출 Leak
  pages/Main/MainAwards.tsx
Labels: bug

#105 [DEV] Project Metadata
  pages/index.tsx
Labels: enhancement

#110 [DEV] Member 페이지 우측 데이터 박스 높이 조정
  pages/Members/MembersDetail.tsx
Labels: enhancement

#111 [FIX] Design 페이지 반응형 레이아웃이 박살났었는데요
  pages/Designs/CrabIntro.tsx
  pages/Designs/LogoIntro.tsx
Labels: bug, enhancement

#112 [FIX] Main 페이지 반응형 레이아웃이 깨졌었는데요
  pages/Main/MainAwards.tsx
Labels: bug, enhancement

#114 [FIX] Designs 페이지 모바일 UI 내 Crab Logo 고장
  pages/Designs/CrabIntro.tsx
Labels: bug, enhancement
